const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const {URL}=require('node:url');
const PORT=Number(process.env.PORT||3001),PUBLIC=path.join(__dirname,'public'),CACHE=path.join(__dirname,'feed-cache.json');
const feeds=[{name:'Hacker News',url:'https://hnrss.org/frontpage',color:'#ff7a45'},{name:'BBC News',url:'http://feeds.bbci.co.uk/news/rss.xml',color:'#b2182b'}];
let cache={items:[],fetchedAt:null,errors:[],loading:false};try{cache={...cache,...JSON.parse(fs.readFileSync(CACHE,'utf8'))}}catch{}
const decode=(v='')=>v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
function tag(b,n){const m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,'i'));return m?decode(m[1]):''}
function parse(xml,source){return[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map((m,i)=>{const b=m[0],link=tag(b,'link');return{id:`${source}-${i}-${link}`,title:tag(b,'title')||'Untitled story',link,date:tag(b,'pubDate')||tag(b,'isoDate')||tag(b,'published'),source}}).filter(x=>x.link)}
async function refresh(){cache.loading=true;const results=await Promise.all(feeds.map(async f=>{try{const r=await fetch(f.url,{headers:{'user-agent':'Local RSS Feed Aggregator/1.0'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return{items:parse(await r.text(),f.name),error:null}}catch(e){return{items:[],error:`${f.name}: ${e.message}`}}}));const seen=new Set();const unique=results.flatMap(x=>x.items).filter(x=>!seen.has(x.link)&&seen.add(x.link));const items=feeds.flatMap(f=>unique.filter(x=>x.source===f.name).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,6)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));cache={items,fetchedAt:new Date().toISOString(),errors:results.map(x=>x.error).filter(Boolean),loading:false};try{fs.writeFileSync(CACHE,JSON.stringify(cache))}catch{}return cache}
function send(res,status,body,type='application/json'){res.writeHead(status,{'content-type':`${type}; charset=utf-8`,'cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(body):body)}
function serve(res,p){const f=path.normalize(path.join(PUBLIC,p==='/'?'/index.html':p));if(!f.startsWith(PUBLIC)||!fs.existsSync(f))return send(res,404,{error:'Not found'});send(res,200,fs.readFileSync(f),{'.html':'text/html','.css':'text/css','.js':'text/javascript'}[path.extname(f)]||'application/octet-stream')}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/api/feeds'){if(!cache.items.length&&!cache.loading)refresh();return send(res,200,{feeds,...cache})}if(u.pathname==='/api/refresh'&&req.method==='POST')return send(res,200,await refresh());serve(res,u.pathname)}).listen(PORT,()=>console.log(`Fast RSS dashboard: http://localhost:${PORT}`));
if(!cache.items.length)refresh().catch(()=>{});else refresh().catch(()=>{});
